config/routes.rb
Rails.application.routes.draw do
  resources :recalls
  resources :products
  resources :medical_devices
  resources :foods
  resources :drugs
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recall.rb
class Recall < ApplicationRecord
  belongs_to :recallable, polymorphic: true
end

app/controllers/recalls_controller.rb
class RecallsController < ApplicationController
  before_action :set_recall, only: [:show, :edit, :update, :destroy]

  # GET /recalls
  # GET /recalls.json
  def index
    @recalls = Recall.all
  end

  # GET /recalls/1
  # GET /recalls/1.json
  def show
  end

  # GET /recalls/new
  def new
    @recall = Recall.new
  end

  # GET /recalls/1/edit
  def edit
  end

  # POST /recalls
  # POST /recalls.json
  def create
    @recall = Recall.new(recall_params)

    respond_to do |format|
      if @recall.save
        format.html { redirect_to @recall, notice: 'Recall was successfully created.' }
        format.json { render :show, status: :created, location: @recall }
      else
        format.html { render :new }
        format.json { render json: @recall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recalls/1
  # PATCH/PUT /recalls/1.json
  def update
    respond_to do |format|
      if @recall.update(recall_params)
        format.html { redirect_to @recall, notice: 'Recall was successfully updated.' }
        format.json { render :show, status: :ok, location: @recall }
      else
        format.html { render :edit }
        format.json { render json: @recall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recalls/1
  # DELETE /recalls/1.json
  def destroy
    @recall.destroy
    respond_to do |format|
      format.html { redirect_to recalls_url, notice: 'Recall was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recall
      @recall = Recall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recall_params
      params.require(:recall).permit(:number, :date, :description, :url, :title, :consumer_contact, :last_publish_date, :number_of_units, :injuries, :hazards, :remedies, :retailers, :country, :recallable_id, :recallable_type)
    end
end

app/helpers/recalls_helper.rb
module RecallsHelper
end

app/views/recalls/_form.html.erb
<%= form_for(recall) do |f| %>
  <% if recall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recall.errors.count, "error") %> prohibited this recall from being saved:</h2>

      <ul>
      <% recall.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :consumer_contact %>
    <%= f.text_area :consumer_contact %>
  </div>

  <div class="field">
    <%= f.label :last_publish_date %>
    <%= f.datetime_select :last_publish_date %>
  </div>

  <div class="field">
    <%= f.label :number_of_units %>
    <%= f.number_field :number_of_units %>
  </div>

  <div class="field">
    <%= f.label :injuries %>
    <%= f.text_area :injuries %>
  </div>

  <div class="field">
    <%= f.label :hazards %>
    <%= f.text_area :hazards %>
  </div>

  <div class="field">
    <%= f.label :remedies %>
    <%= f.text_area :remedies %>
  </div>

  <div class="field">
    <%= f.label :retailers %>
    <%= f.text_area :retailers %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :recallable_id %>
    <%= f.number_field :recallable_id %>
  </div>

  <div class="field">
    <%= f.label :recallable_type %>
    <%= f.text_field :recallable_type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recalls/edit.html.erb
<h1>Editing Recall</h1>

<%= render 'form', recall: @recall %>

<%= link_to 'Show', @recall %> |
<%= link_to 'Back', recalls_path %>

app/views/recalls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recalls</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Date</th>
      <th>Description</th>
      <th>Url</th>
      <th>Title</th>
      <th>Consumer contact</th>
      <th>Last publish date</th>
      <th>Number of units</th>
      <th>Injuries</th>
      <th>Hazards</th>
      <th>Remedies</th>
      <th>Retailers</th>
      <th>Country</th>
      <th>Recallable</th>
      <th>Recallable type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recalls.each do |recall| %>
      <tr>
        <td><%= recall.number %></td>
        <td><%= recall.date %></td>
        <td><%= recall.description %></td>
        <td><%= recall.url %></td>
        <td><%= recall.title %></td>
        <td><%= recall.consumer_contact %></td>
        <td><%= recall.last_publish_date %></td>
        <td><%= recall.number_of_units %></td>
        <td><%= recall.injuries %></td>
        <td><%= recall.hazards %></td>
        <td><%= recall.remedies %></td>
        <td><%= recall.retailers %></td>
        <td><%= recall.country %></td>
        <td><%= recall.recallable_id %></td>
        <td><%= recall.recallable_type %></td>
        <td><%= link_to 'Show', recall %></td>
        <td><%= link_to 'Edit', edit_recall_path(recall) %></td>
        <td><%= link_to 'Destroy', recall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recall', new_recall_path %>

app/views/recalls/new.html.erb
<h1>New Recall</h1>

<%= render 'form', recall: @recall %>

<%= link_to 'Back', recalls_path %>

app/views/recalls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @recall.number %>
</p>

<p>
  <strong>Date:</strong>
  <%= @recall.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recall.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @recall.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @recall.title %>
</p>

<p>
  <strong>Consumer contact:</strong>
  <%= @recall.consumer_contact %>
</p>

<p>
  <strong>Last publish date:</strong>
  <%= @recall.last_publish_date %>
</p>

<p>
  <strong>Number of units:</strong>
  <%= @recall.number_of_units %>
</p>

<p>
  <strong>Injuries:</strong>
  <%= @recall.injuries %>
</p>

<p>
  <strong>Hazards:</strong>
  <%= @recall.hazards %>
</p>

<p>
  <strong>Remedies:</strong>
  <%= @recall.remedies %>
</p>

<p>
  <strong>Retailers:</strong>
  <%= @recall.retailers %>
</p>

<p>
  <strong>Country:</strong>
  <%= @recall.country %>
</p>

<p>
  <strong>Recallable:</strong>
  <%= @recall.recallable_id %>
</p>

<p>
  <strong>Recallable type:</strong>
  <%= @recall.recallable_type %>
</p>

<%= link_to 'Edit', edit_recall_path(@recall) %> |
<%= link_to 'Back', recalls_path %>