config/routes.rb
Rails.application.routes.draw do
  resources :recalls
  resources :products
  resources :medical_devices
  resources :foods
  resources :drugs
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category, optional: true
  has_many :recalls, as: :recallable

  def self.import data_set
    ImportHelper.log_this data_set["enforcement"], self.name, "enforcement"
  end

# not used
  def self.import_new data_set
    unless ImportHelper.log_exists? data_set["enforcement"].first, self.name, "enforcement"
      import data_set
    end
  end

  # I am leaving this method to follow the patter as the others did
  # In case more data is added, this method will act as a controller (see drug.rb)
  # Returns true/false if successful/not
  def self.process data, type
    return process_enforcemnt data
  end

  # Reads and input Json formatted data about Food Enforcements
  # Return true/false if successful/not
  def self.process_enforcemnt data
    # data in json format
    "results": [
      {
        "classification": "Class II",
        "center_classification_date": "20160415",
        "report_date": "20160427",
        "postal_code": "78218-5415",
        "recall_initiation_date": "20160316",
        "recall_number": "F-1083-2016",
        "city": "San Antonio",
        "event_id": "73576",
        "distribution_pattern": "Texas",
        "openfda": {},
        "recalling_firm": "HEB Retail Support Center",
        "voluntary_mandated": "Voluntary: Firm Initiated",
        "state": "TX",
        "reason_for_recall": "The product may have been under processed.",
        "initial_firm_notification": "Two or more of the following: Email, Fax, Letter, Press Release, Telephone, Visit",
        "status": "Ongoing",
        "product_type": "Food",
        "country": "United States",
        "product_description": "Hill Country Fare Chunk Light Tuna in pure vegetable oil NET WT. 5 OZ (142g) packaged in a metal can.",
        "code_info": " UPC 041220653355 lot code 6O9FZ SCEES",
        "address_1": "4710 N Pan Am Expy",
        "address_2": "",
        "product_quantity": "5,376 units"
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :firm, :description, :country, :city, :category_id)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for(food) do |f| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :firm %>
    <%= f.text_field :firm %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :category_id %>
    <%= f.text_field :category_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Firm</th>
      <th>Description</th>
      <th>Country</th>
      <th>City</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.firm %></td>
        <td><%= food.description %></td>
        <td><%= food.country %></td>
        <td><%= food.city %></td>
        <td><%= food.category %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Firm:</strong>
  <%= @food.firm %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food.description %>
</p>

<p>
  <strong>Country:</strong>
  <%= @food.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @food.city %>
</p>

<p>
  <strong>Category:</strong>
  <%= @food.category %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>