config/routes.rb
Rails.application.routes.draw do
  resources :recalls
  resources :products
  resources :medical_devices
  resources :foods
  resources :drugs
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, optional: true
  has_many :recalls, as: :recallable

  # TODO: This version is creating new products for every recall.
  #       Refactor to use existing products with find or create.
  #       Match Product by name, manufacturer and product_type
  def self.import data_set
    data_set.each do |data|
      if data["Products"].empty?
        byebug
      else
        prod_data = data["Products"].first
        product = Product.new(name: prod_data["Name"])
        product.description = prod_data["Descripton"] unless prod_data["Description"].empty? # TODO: might need formating
        product.model = prod_data["Model"] unless prod_data["Model"].empty?
        product.product_type = prod_data["Type"] unless prod_data["Type"].empty?
        product.manufacturer = get_text(data["Manufacturers"], "Name") unless data["Manufacturers"].empty?
        product.manufacturer_countries = get_text(data["ManufacturerCountries"], "Country") unless data["ManufacturerCountries"].empty?

        if product.save
          recall = product.recalls.new(number: data["RecallNumber"],
                                        description: data["Description"],
                                        url: data["URL"],
                                        title: data["Title"],
                                        consumer_contact: data["ConsumerContact"]
                                      )
          recall.date = data["RecallDate"]
          recall.last_publish_date = data["LastPublishDate"]
          # recall.number_of_units = prod_data["NumberOfUnits"].gsub(/[^0-9]/i, '') DEPRECATED: This will have wrong value if there's more than one number in the string. Eg.: "Between 4,000 and 5,000"
          recall.number_of_units = prod_data["NumberOfUnits"]
          recall.injuries = get_text(data["Injuries"], "Name")
          recall.hazards = get_text(data["Hazards"], "Name")
          recall.remedies = get_text(data["Remedies"], "Name")
          recall.retailers = get_text(data["Retailers"], "Name")
          recall.country = product.manufacturer_countries if product.manufacturer_countries
          unless recall.valid?
            puts recall.errors.full_messages.to_sentence
          else
            recall.save
          end
        else
          puts product.errors.full_messages.to_sentence
        end
      end
    end
  end

  def self.get_text list, key
    list.map{|item| item[key]}.join(", ")
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :manufacturer, :manufacturer_countries, :description, :model, :type, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer %>
  </div>

  <div class="field">
    <%= f.label :manufacturer_countries %>
    <%= f.text_field :manufacturer_countries %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="field">
    <%= f.label :category_id %>
    <%= f.text_field :category_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Manufacturer</th>
      <th>Manufacturer countries</th>
      <th>Description</th>
      <th>Model</th>
      <th>Type</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.manufacturer %></td>
        <td><%= product.manufacturer_countries %></td>
        <td><%= product.description %></td>
        <td><%= product.model %></td>
        <td><%= product.type %></td>
        <td><%= product.category %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @product.manufacturer %>
</p>

<p>
  <strong>Manufacturer countries:</strong>
  <%= @product.manufacturer_countries %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Model:</strong>
  <%= @product.model %>
</p>

<p>
  <strong>Type:</strong>
  <%= @product.type %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>